import apiServices from "../../common/apiServices";

// Define the interfaces for authentication requests and responses
export interface SignUpRequest {
  username: string;
  nomPrenom: string;
  phoneNumber: string;
  role: string[];
  password: string;
}

export interface SignInRequest {
  username: string;
  password: string;
}

export interface ResetPasswordRequest {
  username: string;
  nomPrenom: string;
  phoneNumber: string;
  role: string[];
  password: string;
}

// Define the API slice for authentication
const authApiSlice = apiServices
  .enhanceEndpoints({
    addTagTypes: ['Auth'],
  })
  .injectEndpoints({
    endpoints: (builder) => ({
      // Endpoint to sign up a new user
      signUp: builder.mutation<void, SignUpRequest>({
        query: (body) => ({
          url: '/auth/signup',
          method: 'POST',
          body,
        }),
      }),
      // Endpoint to sign out the current user
      signOut: builder.mutation<void, void>({
        query: () => ({
          url: '/auth/signout',
          method: 'POST',
        }),
      }),
      // Endpoint to sign in a user
      signIn: builder.mutation<{ token: string }, SignInRequest>({
        query: (body) => ({
          url: '/auth/signin',
          method: 'POST',
          body,
        }),
      }),
      // Endpoint to reset the user's password
      resetPassword: builder.mutation<void, ResetPasswordRequest>({
        query: (body) => ({
          url: '/auth/resetpassword',
          method: 'POST',
          body,
        }),
      }),
      // Endpoint to refresh the authentication token
      refreshToken: builder.mutation<{ token: string }, void>({
        query: () => ({
          url: '/auth/refreshtoken',
          method: 'POST',
        }),
      }),
    }),
    overrideExisting: false,
  });

// Export hooks generated by createApi for each endpoint
export const {
  useSignUpMutation,
  useSignOutMutation,
  useSignInMutation,
  useResetPasswordMutation,
  useRefreshTokenMutation,
} = authApiSlice;

// Default export for the slice
export default authApiSlice;
