import apiServices from "../../common/apiServices";

// Define the interface for CategoryEventTranslate
export interface CategoryEventTranslate {
  id: number;
  categoryEventTranslate: string;
}
// Define the interfaces for Event and related types
interface PaginatedResponse<T> {
  data: T[];
  currentPage: number;
  totalItems: number;
  totalPages: number;
}

// Define the interface for CategoryEventTranslateDto
export interface CategoryEventTranslateDto {
  id: number;
  categoryEventTranslate: string;
  languageId: number;
  languageName: string;
}

// Define the tag types
export const CATEGORY_EVENT_TRANSLATE_TAGS = ['CategoryEventTranslate'] as const;

// Enhance the API service with additional tag types
const categoryEventTranslateApiSlice = apiServices
  .enhanceEndpoints({
    addTagTypes: CATEGORY_EVENT_TRANSLATE_TAGS,
  })
  .injectEndpoints({
    endpoints: (builder) => ({
    // Endpoint to fetch paginated actions with optional title filtering
    getPaginateCategoryTypeEventsAllOne: builder.query<PaginatedResponse<CategoryEventTranslateDto>, { name?: string; page?: number; size?: number; sort?: string }>({
      query: ({ name = '', page = 0, size = 2, sort = 'id,desc' }) => ({
        url: '/category-event-translatesDtoAll',
        params: { name, page, size, sort },
        method: 'GET',
      }),
      providesTags: [CATEGORY_EVENT_TRANSLATE_TAGS[0]], // Tag for the list of actions
    }),
    }),
    overrideExisting: false,
  });

// Export hooks generated by createApi for each endpoint
export const {
  useGetPaginateCategoryTypeEventsAllOneQuery
} = categoryEventTranslateApiSlice;

// Default export for the slice
export default categoryEventTranslateApiSlice;
