import apiServices from "../../common/apiServices";

// Define the interface for Contact
export interface Contact {
  id: number;
  fullName: string;
  email: string;
  tel: string;
  sujet: string;
  message: string;
  dateCreated: string;
}

// Define the tag types
export const CONTACTS_TAGS = ['Contact'] as const;

// Enhance the API service with additional tag types
const contactsApiSlice = apiServices
  .enhanceEndpoints({
    addTagTypes: CONTACTS_TAGS,
  })
  .injectEndpoints({
    endpoints: (builder) => ({
      // Endpoint to fetch all contacts
      getAllContacts: builder.query<Contact[], void>({
        query: () => ({
          url: '/contacts',
          method: 'GET',
        }),
        providesTags: [CONTACTS_TAGS[0]], // Tag for the list of contacts
      }),
      // Endpoint to fetch a specific contact by ID
      getContactById: builder.query<Contact, number>({
        query: (id) => ({
          url: `/contacts/${id}`,
          method: 'GET',
        }),
        providesTags: (_result, _error, id) => [{ type: CONTACTS_TAGS[0], id }], // Tag for individual contact
      }),
      // Endpoint to create a new contact
      createContact: builder.mutation<Contact, Omit<Contact, 'id' | 'dateCreated'>>({
        query: (contact) => ({
          url: '/contacts',
          method: 'POST',
          data: contact,
        }),
        invalidatesTags: [CONTACTS_TAGS[0]], // Invalidate the entire list of contacts
      }),
      // Endpoint to update an existing contact by ID
      updateContact: builder.mutation<Contact, { id: number; data: Partial<Contact> }>({
        query: ({ id, data }) => ({
          url: `/contacts/${id}`,
          method: 'PUT',
          data: data,
        }),
        invalidatesTags: [CONTACTS_TAGS[0]], // Invalidate the entire list of contacts
      }),
      // Endpoint to delete a contact by ID
      deleteContact: builder.mutation<void, number>({
        query: (id) => ({
          url: `/contacts/${id}`,
          method: 'DELETE',
        }),
        invalidatesTags: [CONTACTS_TAGS[0]], // Invalidate the entire list of contacts
      }),
    }),
    overrideExisting: false,
  });

// Export hooks generated by createApi for each endpoint
export const {
  useGetAllContactsQuery,
  useGetContactByIdQuery,
  useCreateContactMutation,
  useUpdateContactMutation,
  useDeleteContactMutation,
} = contactsApiSlice;

// Default export for the slice
export default contactsApiSlice;
