import apiServices from "../../common/apiServices";

// Define the interface for Mission
export interface Mission {
  id: number;
  title: string;
  description: any;
}
// Define the DTO interface for About Us
export interface MissionDto {
  id: number;
  title: string;
  description: any;
  languageId: number;
  languageName: string;
  imageProfileId: number;
  imageData: any; // Use Uint8Array for binary data
}

// Define the tag types
export const MISSION_TAGS = ['Missions'] as const;

// Enhance the API service with additional tag types
const missionsApiSlice = apiServices
  .enhanceEndpoints({
    addTagTypes: MISSION_TAGS,
  })
  .injectEndpoints({
    endpoints: (builder) => ({
      // Query to fetch About Us entries filtered by language
    getMissionByLanguage: builder.query<MissionDto[], string>({
      query: (languageName) => ({
        url: `/missionsAllFilter`,
        method: 'GET',
        params: {languageName}, // Pass the languageName as a query parameter
      }),
      providesTags: [MISSION_TAGS[0]], // Tag for the list of missions
    }),
      
    }),
    overrideExisting: false,
  });

// Export hooks generated by createApi for each endpoint
export const {
  useGetMissionByLanguageQuery 
} = missionsApiSlice;

// Default export for the slice
export default missionsApiSlice;
